---
- hosts: 192.168.56.111
  remote_user: root
  tasks:

#  - name: Keyring Installation
#    apt: name=ubuntu-cloud-keyring state=present


#  - name: Upgrade
#    apt: upgrade=dist
#    apt: update_cache=yes cache_valid_time=360
#    me: Install Python Keystone client
#    apt: name=python-keystoneclient state=present0

#  - name: Installing mariadb-server
#    apt: name=mariadb-server state=present

#  - name: Installing python-mysqldb
#    apt: name=python-mysqldb state=present

#  - name: Rebbit MQ Server
#    apt: name=rabbitmq-server state=present

#  - name: Install MySQl Server
#    apt: name=mysql-server state=present

#  - name: Ensure Mysql is Running
#    service: name=mysql state=started

#  - name: Ensure Rebbit MQ Server is Running
#    service: name=rabbitmq-server state=started
        
#  - name: Set guest password for RabbitMQ
#    command: rabbitmqctl change_password guest RABBIT_PASS 

#  - name: Copy templet k.cnf from /etc/ansible/roles/common/files/k.conf
#    copy: src=/etc/ansible/roles/common/files/keystone.conf dest=/etc/keystone/keystone.conf owner=root group=root mode=0644

  - name: Create DB 
    mysql_db: name=keystone state=present

  - name: Executing Grants for keystone DB
    command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'KEYSTONE_DBPASS'; "
    command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY 'KEYSTONE_DBPASS';"
  
  - name: Install Python Keystone client
    apt: name=python-keystoneclient state=present force=yes

  - name: Install Keystone
    apt: name=keystone state=present force=yes
    
  - name: Ensure Keystone is Running
    service: name=keystone state=started
